name: rest-api

services:
  rest-api:
    build: .
    environment:
      - DB_PATH=/app/data/db.sqlite
    volumes:
      - /root/data:/app/data
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
