name: rest-api

services:
  rest-api:
    build: .
    environment:
      - DB_PATH=/data/database.sqlite
    volumes:
      - /root/data:/app/dist/models/data/
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
