name: rest-api

services:
  rest-api:
    image: ghcr.io/multifacs/cogni-db-ghcr:latest
    build: .
    environment:
      - DB_PATH=/app/data/db.sqlite
      - MODE=PROD
      - VAPID_PUBLIC_KEY=BM_scxMu6VHhleeNYjLTsc-XCpwYa_59VQYCdZiDOnfuwVlcmHivUqrK2FiwnK-wdXe9ROj7hRSMPruMEQCZrjs
      - VAPID_PRIVATE_KEY=vEwbPpKPNWNdzxAjKGt1W4sFgFckOPmxNnWLf1YSI0k
    volumes:
      - /root/data:/app/data
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

  db-viewer:
    image: coleifer/sqlite-web:latest
    ports:
      - 8012:8080
    volumes:
      - /root/data:/data
    environment:
      - SQLITE_DATABASE=db.sqlite
